POLLBOOTH/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='details'),
    path('<int:pk>/result/', views.ResultView.as_view(), name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    ]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=2083)
    publishing_date = models.DateTimeField('Date Published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() - datetime.timedelta(days=1) <= self.publishing_date <= timezone.now()


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes_count = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.template import loader
from .models import Question, Choice
from django.views import generic


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "question_set"

    def get_queryset(self):
        return Question.objects.filter(publishing_date__lte=timezone.now())


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/details.html"


class ResultView(generic.DetailView):
    model = Question
    template_name = "polls/result.html"


#def index(request):
    #question_set = Question.objects.all()
    #template = loader.get_template('polls/index.html')
    #context = {'question_set': question_set}
    # SHORTCUT for RENDERING Context with template is as below:
    # return render(request, 'polls/index.html', context)
    #return HttpResponse(template.render(context, request))


#def details(request, question_id):
    #try:
     #   question = Question.objects.get(pk=question_id)
    #except Question.DoesNotExist:
     #   raise Http404("Question Does not Exist")
    # There is a shortcut in Django for getting an object and returning http404 error if object doesn't exist
    # The above four lines could be replaced as below
    # question = get_object_or_404(Question, pk=Question_id)
    #return render(request, "polls/details.html", {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', {'question': question, 'error_message': 'Please Select a choice' })
    else:
        selected_choice.votes_count += 1
        selected_choice.save()
        return redirect('polls:result', question_id)


#def result(request, question_id):
    #question = get_object_or_404(Question, pk=question_id)
    #return render(request, "polls/result.html", {'question': question})

polls/templates/polls/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QUESTION{{ question.id }}</title>
</head>
<body>

    {% if error_message %}
    <h1> {{ error_message }}</h1>
    {% endif %}
    <h2> {{ question.question_text }} </h2>
    <form action=" {% url 'polls:vote' question.id %}" method="post">
<!--         forms with post method should contain the template tag {% csrf_token %} for protection against cross site forgeries-->
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="vote">
    </form>


</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<head>
    <meta charset="UTF-8">
    <title>POLLS BOOTH</title>
</head>
<body>
    <h1>WELCOME TO POLLING BOOTH</h1>
    {% if question_set %}
    <ul>
        {% for question in question_set %}
        <li>
            <a href="{% url 'polls:details' question.id %}" target="_blank"> {{ question.question_text }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        No Polls are Available.
    {% endif %}
</body>
</html>

polls/templates/polls/result.html
<h1> POLL RESULTS. </h1>
<h2> {{question.question_text}} </h2>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text}} - {{ choice.votes_count }} vote{{ choice.votes_count|pluralize}}</li>
        <br>
        {% endfor %}
    </ul>
<a href="{% url 'polls:index'%}"> Take another poll </a>